#default config file ( default.conf ) located at /etc/nginx/conf.d in the nginx container

server {
    listen       8080;
    listen  [::]:8080;
    server_name  webserv;

    #access_log  /var/log/nginx/host.access.log  main;

    location / { #how the server should respond to requests for the root path
        root   /www/html; #specifies where the server will search for files (document root)
        index  index.html; #means if a directory is requested, serve the index.html or index.htm file
    }

    location /upload {
        root /www/uploads;
        accepted_methods POST GET DELETE;
        limit_client_body_size 10M;
    }

    error_page  404              /404.html; #Specifies custom pages for certain HTTP error codes

    # redirect server error pages to the static page /50x.html
    #
    # error_page   500 502 503 504  /50x.html;
    # location = /50x.html {
    #     root   /usr/share/nginx/html;
    # }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}


